add missing ninja dependency to docs
While  in a ubuntu 18-04 docker container, I got
```
cd /keystone-data/keystone/qemu && ./configure --target-list=riscv64-softmmu,riscv64-linux-user
Using './build' as the directory for build output

ERROR: Cannot find Ninja

CMakeFiles/qemu.dir/build.make:68: recipe for target '../qemu/build/config-host.mak' failed
make[2]: *** [../qemu/build/config-host.mak] Error 1
make[2]: Leaving directory '/keystone-data/keystone/build'
CMakeFiles/Makefile2:236: recipe for target 'CMakeFiles/qemu.dir/all' failed
make[1]: *** [CMakeFiles/qemu.dir/all] Error 2
make[1]: Leaving directory '/keystone-data/keystone/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
```